services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data
      - ./config/initializers/init.sql:/docker-entrypoint-initdb.d/init.sql

  ruby:
    build: .
    container_name: ruby
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ${PWD}:/app
      - ruby-gems:/usr/local/bundle
    ports:
      - "3000:3000"
    working_dir: /app
    stdin_open: true
    tty: true
    command: bundle exec puma -p 3000
    depends_on:
      - redis

  sidekiq:
    image: ruby
    container_name: sidekiq
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ${PWD}:/app
      - ruby-gems:/usr/local/bundle
    working_dir: /app
    stdin_open: true
    tty: true
    command: sidekiq -r ./lib/jobs/import_data_job.rb
    depends_on:
      - redis
  
  redis:
    image: redis

volumes:
  data-db:
  ruby-gems: