services:
  postgres-developent:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data
      - ./config/initializers/create_exames_table.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-sinatra
    
  postgres-test:
    image: postgres
    container_name: postgres-test
    environment:
      POSTGRES_USER: postgres-test
      POSTGRES_PASSWORD: '654321'
    ports:
      - "5433:5432"
    volumes:
      - ./config/initializers/create_exames_table.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-sinatra

  ruby:
    build: .
    container_name: ruby
    volumes:
      - ${PWD}:/app
      - ruby-gems:/usr/local/bundle
    ports:
      - "3000:3000"
      - "4444:4444"
    working_dir: /app
    networks:
      - postgres-sinatra
    stdin_open: true
    tty: true
    command: bash

networks:
  postgres-sinatra:

volumes:
  data-db:
  ruby-gems: